[package]
name = "rtd-package-alt"
version.workspace = true
authors = ["LinkU Labs"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
indexmap.workspace = true
move-compiler.workspace = true
move-package-alt.workspace = true
serde.workspace = true
rtd-package-management.workspace = true
rtd-protocol-config.workspace = true
rtd-rpc-api.workspace = true
rtd-sdk.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
