[package]
name = "rtd-metrics-push-client"
authors = ["LinkU Labs"]
license = "Apache-2.0"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
prometheus.workspace = true
reqwest.workspace = true
snap.workspace = true
tokio.workspace = true
tracing.workspace = true

fastcrypto.workspace = true
linku-metrics.workspace = true
rtd-tls.workspace = true
rtd-types.workspace = true
