[package]
name = "rtd-name-service"
version.workspace = true
authors = ["LinkU Labs"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
bcs.workspace = true
serde.workspace = true
thiserror.workspace = true

move-core-types.workspace = true

rtd-types.workspace = true
