[package]
name = "test-cluster"
authors = ["LinkU Labs <build@linkuverse.com>"]
version = "0.1.0"
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
consensus-config.workspace = true
fastcrypto-zkp.workspace = true
futures.workspace = true
tracing.workspace = true
jsonrpsee.workspace = true
tokio = { workspace = true, features = ["full", "tracing", "test-util"] }
tonic.workspace = true
rand.workspace = true
rtd-config.workspace = true
rtd-core.workspace = true
linku-common.workspace = true
rtd-framework.workspace = true
rtd-swarm-config.workspace = true
rtd-json-rpc-types.workspace = true
rtd-node.workspace = true
rtd-protocol-config.workspace = true
rtd-swarm.workspace = true
rtd-types.workspace = true
rtd-keys.workspace = true
rtd-sdk.workspace = true
rtd-test-transaction-builder.workspace = true
rtd-rpc-api.workspace = true

move-binary-format.workspace = true
move-core-types.workspace = true

[target.'cfg(msim)'.dependencies]
rtd-simulator.workspace = true
prometheus.workspace = true

[dev-dependencies]
rtd-macros.workspace = true
