[package]
name = "rtd-adapter-v3"
version = "0.1.0"
authors = ["LinkU Labs"]
description = "Adapter and accompanying CLI for local rtd development"
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
bcs.workspace = true
leb128.workspace = true
tracing.workspace = true
serde.workspace = true
indexmap.workspace = true
serde_json.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-trace-format.workspace = true
move-vm-config.workspace = true
linku-common.workspace = true
linku-metrics.workspace = true
nonempty.workspace = true

move-bytecode-verifier = { path = "../../../../external-crates/move/historical-versions/v3/crates/move-bytecode-verifier", package = "move-bytecode-verifier-v3" }
move-vm-runtime = { path = "../../../../external-crates/move/historical-versions/v3/crates/move-vm-runtime", package = "move-vm-runtime-v3" }
move-vm-profiler = { path = "../../../../external-crates/move/crates/move-vm-profiler" }
rtd-move-natives = { path = "../rtd-move-natives", package = "rtd-move-natives-v3" }
rtd-verifier = { path = "../rtd-verifier", package = "rtd-verifier-v3" }
move-vm-types = { path = "../../../../external-crates/move/historical-versions/v3/crates/move-vm-types", package = "move-vm-types-v3" }
move-regex-borrow-graph = { path = "../../../../external-crates/move/crates/move-regex-borrow-graph" }

rtd-macros.workspace = true
rtd-protocol-config.workspace = true
rtd-types.workspace = true
parking_lot.workspace = true
either.workspace = true

[features]
tracing = [
    "rtd-types/tracing",
    "move-vm-runtime/tracing",
    "move-vm-profiler/tracing",
    "move-vm-config/tracing",
]
