# Copyright (c) LinkU Labs, Inc.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "authenticated_event"
edition = "2024.beta"

[dependencies]
Rtd = { local = "../../../../rtd-framework/packages/rtd-framework" }

[addresses]
authenticated_event = "0x0"
