[package]
name = "rtd-indexer-alt-metrics"
version.workspace = true
authors = ["LinkU Labs <build@linkuverse.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
prometheus.workspace = true
prometheus-closure-metric.workspace = true
tokio.workspace = true
tracing.workspace = true

rtd-futures.workspace = true
rtd-pg-db.workspace = true
